version: '3'
services:
  webapp:
    image: elastest/demo-web-java-test-sut-offline
    expose: 
        - 8080
    network_mode: bridge
    logging:
      driver: syslog
      options:
        syslog-address: tcp://localhost:5000
