version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
    ports:
        - "9200:9200"
        - "9300:9300"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.3
    environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
        - "5601:5601"
    depends_on:
        - elasticsearch
  logstash:
    image: edujgurjc/eslogstash
    depends_on:
        - elasticsearch
    ports:
        - "5000:5000"
    environment:
        - ESHOST=elasticsearch
        - ESINDEX=webapp
