node{
    elastest(tss: ['EUS']) {
        stage ('Executing Test') {
            echo 'Print env variables'
            sh 'env'
            echo 'Set up test environment'
            mvnHome = tool 'M3.3.9'
            echo 'Cloning repository'
            git 'https://github.com/elastest/demo-projects'
            echo 'Run test'
            sh "cd ./simple-web-java-test/;'${mvnHome}/bin/mvn' test"
        }        
    }
}